name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker stop simple_api && docker rm simple_api && docker rmi simple_api:latest  && docker build . --file Dockerfile --tag simple_api:latest
      - name: Run the Docker image
        run: docker run -d -p 3001:3001 --name simple_api simple_api:latest
